version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: usuario
      MYSQL_USER: Romario
      MYSQL_PASSWORD: 1234

  word-image:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
