version: '3.1'
services:
  word-image:
  build: .
  depends_on:
    -mysql-image
  

  mysql-image:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    enviroment:
      MYSQL_DATABASE: usuario
      MYSQL_USER: Romario
      MYSQL_PASSWORD: 1234
    ports:
    - "80:80"
    
